import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from './lib/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  manifest: '/manifest.json',
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
  themeColor: '#0E1017',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider>
          <main className="flex min-h-screen flex-col items-center justify-between p-24">
            <div className="w-[393px] h-[852px] relative mobile-body rounded-[40px]">
            {children}
            </div>
            </main>
        </AuthProvider>
        </body>
    </html>
  )
}
